apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-0
  description: python-app-0  Demo App with custom python template
  annotations:
     github.com/project-slug: priti-devops-org-94/python-app-0
     backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
